# -*- coding: utf-8 -*-
"""Matplotlib_class1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p3CKIZWHi4jzvNxZe2iXUeB7RGO44aTt

# Introduction to Matplotlib (welcome back Sher)

Matplotlib is one of the most widely used **data visualization libraries in Python**.  
It provides a flexible and powerful way to create plots, graphs, and charts, helping us **understand patterns, trends, and insights** in data.

---

## Key Points

- **Library type**: Low-level plotting library  
- **Core Idea**: Gives full control over every element of a figure (titles, axes, labels, colors, styles, etc.)  
- **Origin**: Inspired by MATLAB’s plotting system, hence its name **Matplotlib**  
- **Flexibility**: Can create anything from simple line plots to highly customized multi-plot figures  
- **Integration**: Works seamlessly with NumPy, Pandas, and SciPy

---

## Why Use Matplotlib?

- To **visualize data** effectively before analysis and modeling  
- To create **publication-quality figures**  
- To **customize every detail** of plots (size, colors, fonts, legends, grids)  
- Acts as the **foundation** for other visualization libraries like **Seaborn**, **Pandas .plot()**, and **Plotly (partially inspired)**

---

## Anatomy of a Matplotlib Figure

A Matplotlib figure consists of several key components:

1. **Figure** → The whole window or page that contains everything  
2. **Axes** → The actual area where data is plotted (x-axis, y-axis)  
3. **Axis** → The scales and ticks for x and y directions  
4. **Plot elements** → Titles, labels, legends, lines, bars, markers, etc.

---

## Typical Workflow

1. **Import the library**  
   ```python
   import matplotlib.pyplot as plt

### Basic Example: Plotting Two Arrays
python
Copy code
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""### Canvas in Matplotlib

A **canvas** is the entire drawing area where all your plots live
think of it as a blank sheet of paper on which you can add one or many plots.

You create a canvas with `plt.figure()` or `plt.subplots()`.
"""

x = [1,2,3,4,5]
y1 = [1,3,7,16,27]
y2 = [1,4,9,16,25]
plt.plot(x,y1)
plt.plot(x,y2)
plt.title("GRAPH")
plt.ylabel("Mark")
plt.xlabel("Count")
#NOTE: Common mistake if you by chance save it , go to run time , restart session or else it will give an error to run a str value , so you need to keep in mind of syntax.

plt.figure(figsize=(8,7))
plt.plot(x,y1)
plt.plot(x,y2)
plt.xlabel("age")
plt.ylabel("score")
plt.grid(True)
plt.title('Age V/S Score')

"""###  Subplots with `plt.subplot()`

`plt.subplot()` is a **simple way** to place multiple plots on one figure.

- Syntax: `plt.subplot(nrows, ncols, index)`  
- It splits the figure into a grid (`nrows` × `ncols`)  
- `index` tells which cell to draw in (counted left → right, top → bottom)
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

x = [1,2,3,4,5]
y1 = [1,3,7,16,27]
y2 = [1,4,9,16,25]
plt.figure(figsize=(12,10))

plt.subplot(2,2,1)
plt.plot(x,y1)
plt.xlabel("Time")
plt.ylabel("marks")

plt.subplot(2,2,4)
plt.plot(x,y2)
plt.xlabel("years")
plt.ylabel("score")

"""### Matplotlib Object-Oriented Interface

Instead of using only `plt` commands, the **OO style** gives more control:

1. Create a **Figure** → acts as the **canvas**  
2. Add one or more **Axes** → areas where plots live  

This is preferred for professional or complex visualizations.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

x = [1,2,3,4,5]
y1 = [1,3,7,16,27]
y2 = [1,4,9,16,25]

fig = plt.figure(figsize=(8,6)) #here fig variable is an object , plt.stuff is class , stored in the object.

ax = fig.add_axes([0.1,0.1,0.8,0.8]) #here it denotes position[left,bottom,height,width]
ax2 = fig.add_axes([0.2,0.5,0.4,0.4]) #here it denotes position[left,bottom,height,width]
ax.plot(x,y1)
ax2.plot(x,y2)

"""### Code is a little more complicated, but the advantage is that we now have full control of where the plot axes are placed, and we can easily add more than one axis to the figure:"""



"""### Figure Size, Aspect Ratio & DPI in Matplotlib

- **Figure Size** → Width × Height of the canvas (in inches)  
- **Aspect Ratio** → Relationship between width and height  
- **DPI (Dots Per Inch)** → Resolution (number of pixels per inch)

These settings help you control how large and sharp your plots appear.
python
Copy code

"""

x = [1,2,3,4,5]
y1 = [1,3,7,16,27]
y2 = [1,4,9,16,25]

plt.figure(figsize=(8,6),dpi=120)
plt.plot(x,y)

"""### Legends, Labels & Title

Matplotlib lets you describe your plot with:
- **Title** → Explains what the plot shows  
- **Axis Labels** → Describe x-axis & y-axis  
- **Legend** → Identifies different lines or markers

"""

x = [1,2,3,4,5]
y = [2,4,6,8,10]

plt.figure(figsize=(7,4))
plt.xlabel="X-axis"
plt.ylabel="Y-axis"
plt.title("Title,Labels & Legends")
#plot first line
plt.plot(x,y1,color="blue",marker="o",label="Square")
#plot second line
plt.plot(x,y2,color="red",marker="s",label="Line")
plt.legend(loc ="upper left")

"""### Line Styles, Colors, Widths & Markers

Matplotlib lets you customize almost every visual property of a line:
- **Color** (`color=` or `c=`)
- **Line Width** (`linewidth=` or `lw=`)
- **Line Style** (`linestyle=` or `ls=`)
- **Markers** (`marker=`, `markersize=`, `markerfacecolor=`, etc.)
"""

import matplotlib.pyplot as plt

# Sample data
x = [0, 1, 2, 3, 4, 5]

fig, ax = plt.subplots(figsize=(12, 6))

# Different line widths (all in orange)
ax.plot(x, [v + 1 for v in x], color="orange", linewidth=0.5, label="width=0.5")
ax.plot(x, [v + 2 for v in x], color="orange", linewidth=1.5, label="width=1.5")
ax.plot(x, [v + 3 for v in x], color="orange", linewidth=3, label="width=3")

# Line styles with constant width
ax.plot(x, [v + 4 for v in x], color="green", lw=2, linestyle='-')    # solid
ax.plot(x, [v + 5 for v in x], color="green", lw=2, linestyle='--')   # dashed
ax.plot(x, [v + 6 for v in x], color="green", lw=2, linestyle='-.')   # dash-dot
ax.plot(x, [v + 7 for v in x], color="green", lw=2, linestyle=':')    # dotted

# Custom dash pattern
line, = ax.plot(x, [v + 8 for v in x], color="black", lw=2)
line.set_dashes([10, 5, 2, 5])  # dash, space, dash, space...

# Marker styles with a blue line
ax.plot(x, [v + 9 for v in x], color="blue", lw=2, ls='-', marker='o', label="circle")
ax.plot(x, [v + 10 for v in x], color="blue", lw=2, ls='--', marker='s', label="square")
ax.plot(x, [v + 11 for v in x], color="blue", lw=2, ls='-', marker='*', label="star")
ax.plot(x, [v + 12 for v in x], color="blue", lw=2, ls=':', marker='x', label="x-mark")

# Playing with marker size & colors
ax.plot(x, [v + 13 for v in x], color="purple", lw=1, ls='-', marker='o', markersize=3)
ax.plot(x, [v + 14 for v in x], color="purple", lw=1, ls='-', marker='o', markersize=6)
ax.plot(x, [v + 15 for v in x], color="purple", lw=1, ls='-', marker='o',
        markersize=8, markerfacecolor="yellow", markeredgewidth=2, markeredgecolor="red")

# Final touches
ax.set_title("Line Styles, Colors, Widths & Markers", fontsize=14)
ax.set_xlabel("X-axis")
ax.set_ylabel("Y-axis")
ax.grid(True)
ax.legend(loc="upper left", fontsize=9)

plt.show()

"""### Setting Plot Range (Axis Limits)

You can control how much of your data is visible by setting **x-axis** and **y-axis** limits.

Matplotlib provides:
- `plt.xlim()` / `plt.ylim()` → Quick way  
- `ax.set_xlim()` / `ax.set_ylim()` → Object-Oriented way

"""

x = [1,2,3,4,5]
y = [1,4,9,16,25]

fig , ax = plt.subplots(figsize=(7,4))

ax.plot(x,y,color='teal',marker='o',linewidth=2)

ax.set_xlim(-1,6)
ax.set_ylim(-5,30)

"""### 🌟 Special Plot Types: Scatter, Histogram & Boxplot

"""

x = [1,2,3,4,5]
y = [5,7,4,6,8]

plt.figure(figsize=(12,4))
plt.subplot(1,3,1)
plt.scatter(x,y)
plt.subplot(1,3,2)
plt.hist(x) #histogram - only x as input
plt.subplot(1,3,3)
plt.boxplot(x)

"""> ✅ **Note:**  
> Scatter plots, histograms, and boxplots are available in Matplotlib — but libraries like **Seaborn** make these (and many more) much easier, prettier, and require less code.  
>
> For now, this is all you really need from Matplotlib regarding these plot types.  
> Let’s move on and explore **Seaborn** to see how it simplifies and enhances our visualizations!

"""

